name: UltimatePrivateMines
main: games.negative.mines.UPMPlugin
version: '${project.version}'
authors: [ "ericlmao" ]
api-version: 1.20

depend: ["FastAsyncWorldEdit"]
softdepend: ["SuperVanish", "PremiumVanish"]